#!/bin/bash
#
# Writes Generated/BuildInfo.generated.swift with the git short SHA of the tree
# a build came from. Wired in as the CalPeek target's pre-build phase, so the
# value is current for every build and lands well before the Sources phase.
#
# Release deliberately never shells out to git: archive and App Store builds
# must not depend on a .git directory existing (a source export or CI checkout
# may not have one), and the SHA is only ever displayed by Debug builds — see
# the `#if DEBUG` menu header in AppDelegate. Release gets an empty string.
#
set -euo pipefail

ROOT="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
OUT_DIR="$ROOT/Generated"
OUT="$OUT_DIR/BuildInfo.generated.swift"

sha=""
if [ "${CONFIGURATION:-Debug}" = "Debug" ]; then
    # Every git call is `|| true`: a missing .git must degrade to an empty
    # SHA, never fail the build.
    sha="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || true)"
    if [ -n "$sha" ] && [ -n "$(git -C "$ROOT" status --porcelain 2>/dev/null || true)" ]; then
        sha="$sha-dirty"
    fi
fi

mkdir -p "$OUT_DIR"

cat > "$OUT.tmp" <<EOF
// Generated by Scripts/generate-build-info.sh — do not edit, do not commit.

enum BuildInfo {
    /// Git short SHA of the tree this build came from, suffixed \`-dirty\` when
    /// the working tree had uncommitted changes. Empty in Release, which never
    /// invokes git.
    static let gitSHA = "$sha"
}
EOF

# Only replace the file when the contents actually changed — an unchanged SHA
# must not touch the mtime, or every build would recompile everything that
# depends on this file.
if cmp -s "$OUT.tmp" "$OUT" 2>/dev/null; then
    rm -f "$OUT.tmp"
else
    mv "$OUT.tmp" "$OUT"
fi
